### ISSUE TITLE
npm package is out of date, version 3.0.0 from npm is broken

### ISSUE THREAD

**Issue by KenEucker** [sindresorhus/strip-bom#10]
Should npm be updated to the most recent version of the code or possibly reverted back to a stable version?

I recently updated to version 3.0.0 from 2.0.0 but it appears that it is now broken. I get the error: "Expected a string, got object". Using the code here on github directly, not through npm, also breaks with the same error. 

I will revert back to 2.0.0 for now.

**Comment by sindresorhus** [comment]
The package was split into two packages for version 3. This package handles string input and https://github.com/sindresorhus/strip-bom-buf handles buffers.
