### ISSUE TITLE
What is the benefit of using arrow function while exporting?

### ISSUE THREAD

**Issue by sarbbottam** [sindresorhus/strip-bom#6]
**This issue is not related to the functionality of this module.**

---

What is the benefit of arrow function 
```js
module.exports = x => {
	...
	return x;
};
```
over

```js
module.exports = function (x) {
	...
	return x;
};
```

when exporting.

---

[I had been using arrow functions](https://github.com/sarbbottam/interview-questions/commit/137fe4f63a31844f6df8769ffa9465cebf9ced95) every where possible, but did not find it useful, thus changed it.

---

Does it emphasize that when ever there is a `anonymous function` or `function expression` use `arrow function`?

**Comment by SamVerschueren** [comment]
I think it's just a personal taste to be honest. But if you choose one over the other, be consistent. Personally I prefer the fat-arrow function.

**Comment by sindresorhus** [comment]
Shorter and lexical scoping: http://bfy.tw/6cSm

**Comment by sarbbottam** [comment]
Thanks!

**Comment by sarbbottam** [comment]
> Shorter and lexical scoping: http://bfy.tw/6cSm

Not sure, if I follow the benefit of `lexical scoping` in `module.exports`, I did `google` but did not find any convincing answer, other than what @SamVerschueren stated

> I think it's just a personal taste to be honest.

I thought it's better to get expert's suggestion. 
I didn't expect http://bfy.tw/6cSm to be LMGTFY, closing the issue w/o any comment wound have been less insulting.

**Comment by sindresorhus** [comment]
Wasn't meant to be insulting...

**Comment by Firesphere** [comment]
This choice is actually breaking my build, as uncss is refusing to work in Windows native Bash, due to unexpected token.

**Comment by SamVerschueren** [comment]
Upgrade Node.js to 4+

**Comment by Firesphere** [comment]
That's not really an option with the native Bash for Windows. It does work in Ming and git bash though.
