### ISSUE TITLE
transpile source to es5?

### ISSUE THREAD

**Issue by Kflash** [sindresorhus/strip-bom#7]
Hey. I'm developing a project that need to work for nodeJS 0.12. And I'm using latest ESLint version. This version of ESLint uses your script, but on nodeJS 0.12, it throws this:

```
eslint/node_modules/strip-bom/index.js:2
module.exports = x => {
                   ^^
```
Older versions of ESLint works fine, but not version 3.x.

Any possibility to convert to ES5 ?

**Comment by SamVerschueren** [comment]
Install version `2.0.0` and you are good to go.

**Comment by Kflash** [comment]
@SamVerschueren Well. ESLint are using v. 3.0.0.
Just to check this I installed the same version locale, and index.js is still ES6, not ES5.

But NP I can open an issue ticket and ask ESLint to switch out that package.
